import { MDXRenderer } from '@/components/MDXRenderer'
import { MermaidDiagram } from '@/components/diagrams/MermaidDiagram'

export const metadata = {
  title: 'Bridges & Engine Integration - DeepBl4nder',
  description: 'How DeepBl4nder connects to Blender through a validated, security-first bridge abstraction.',
}

const mermaidChart1 = `graph TB
    subgraph Agents["Agent Layer"]
      BA["BlenderAgent"]
    end

    subgraph Bridges["Bridge Layer"]
      BB["BlenderBridge"]
    end

    subgraph Engines["External Engines"]
      BLENDER["Blender 4.1+"]
    end

    BA --> BB
    BB --> BLENDER
  `

const mermaidChart2 = `graph TB
    subgraph Docker["Docker Compose"]
      subgraph Core["Core Services"]
        LLM["llm-server :8080<br/>(optional local inference)"]
        BW["blender-worker"]
      end
    end

    LLM --> BW
  `

const section1 = `
# Bridges & Engine Integration: The Abstraction Layer

At the heart of a robust 3D production system lies the question of how agents communicate with the 3D engine without being coupled to its quirks. DeepBl4nder solves this through the **bridge pattern**, an abstraction layer that provides a uniform interface to the external engine while handling the messy reality of validation, security, and process isolation behind the scenes.

A bridge is not merely a wrapper. It is a boundary that enforces security policies, validates generated code, manages process lifecycles, and isolates the agent runtime from the external engine. When a BlenderAgent generates a Python script, that script does not execute directly in the agent's process. It passes through BlenderBridge, which validates it via AST analysis, writes it to a temporary file, and launches Blender in headless mode to execute it. This separation is not ceremony — it is the architectural spine that keeps the system safe and maintainable.

## Why Bridges Exist as an Abstraction Layer

The decision to introduce a bridge layer was driven by three observations about the problem domain. First, running Blender involves a heterogeneous toolchain: Python scripts, headless subprocess execution, GPU backends (CUDA, OptiX, HIP, Metal), and OS-specific paths. A bridge normalizes all of that behind one interface.

Second, the security considerations are real. BlenderBridge executes Python code in a subprocess — it needs AST validation to prevent malicious or dangerous operations. Each bridge must enforce the security model appropriate to its engine.

Third, engines have lifecycle requirements. Blender must be launched fresh for each script execution or kept running as a persistent service. The bridge layer manages these lifecycle differences so that agents do not need to know whether Blender is running locally or in Docker.
`

const section2 = `
The result is that an agent can write \`bridge.execute_python(script)\` without knowing whether Blender is running locally or in Docker, whether it uses CUDA or CPU rendering, or what operating system the host uses. The bridge absorbs all of that complexity.

## BlenderBridge: The Primary Engine

BlenderBridge is the heart of the rendering pipeline. Rather than receiving commands over a network, Blender executes Python scripts. This means BlenderBridge must handle script validation, file management, subprocess orchestration, and output verification.

### The Validation-First Architecture

Every script that passes through BlenderBridge is validated before execution. This is not a suggestion or a best practice — it is a hard requirement enforced at the bridge level. The bridge calls \`validate_for_worker()\` on the script, which runs the AST validator against the CodePolicy. If validation fails, the script is never executed. Period.

This design is rooted in the **fail-closed** principle: when in doubt, do not execute. The system assumes that generated code is potentially dangerous until proven otherwise. This is the opposite of the fail-open approach, which would allow code to run unless it is known to be dangerous. The fail-closed approach is more conservative, but it is the only approach that provides meaningful security guarantees when the code is generated by an LLM.

\`\`\`python
from DeepBl4nder.bridges.blender.bridge import BlenderBridge
from DeepBl4nder.domain.scene import BlenderScript

bridge = BlenderBridge(blender_exe="/usr/local/bin/blender")

# Create a script to execute
script = BlenderScript(
    code="import bpy\\nbpy.ops.mesh.primitive_cube_add()",
    scene_name="test",
    version=1,
)

# BlenderBridge validates before execution
# If validation fails, CodePolicyViolation is raised
result = bridge.run_script(script, workdir=Path("/tmp/output"))
\`\`\`

The validation pipeline has multiple layers. The AST parser checks that the code is syntactically valid Python. The CodePolicy checks that only allowed modules are imported. The forbidden builtins check blocks \`exec()\`, \`eval()\`, \`compile()\`, and other dangerous functions. The forbidden attributes check blocks \`os.system()\`, \`subprocess.Popen()\`, and similar system-level calls. And the semantic quality checks warn about common issues like missing render output paths, unset render engines, and missing camera setups.

### GPU Detection and Backend Selection

BlenderBridge automatically detects the available GPU backend — CUDA, OptiX, HIP, or Metal — and configures Blender to use it. This detection happens at initialization time, not at execution time, so there is no overhead during rendering.

The detection logic probes the system using platform-specific tools: \`nvidia-smi\` for NVIDIA GPUs, \`rocm-smi\` for AMD GPUs on Linux, and \`system_profiler\` for Apple Silicon on macOS. When an NVIDIA GPU is detected, the bridge prefers OptiX over CUDA because OptiX provides better ray tracing performance on RTX hardware.

The detected backend is communicated to Blender through environment variables rather than script modifications. This keeps the generated scripts clean and engine-agnostic — the same script runs on any platform, and the bridge handles the GPU configuration transparently.

### Headless Execution

BlenderBridge runs Blender in headless mode (\`blender -b -P <script>\`), which means Blender executes the script without opening a window. This is essential for server-side operation, Docker containers, and CI/CD pipelines. The bridge manages the subprocess lifecycle: it launches Blender with a configurable timeout (defaulting to 600 seconds for production renders), captures stdout and stderr, and returns a structured \`ProcessResult\`.

The timeout is deliberately generous. Production renders with 256+ samples, complex lighting, and high-resolution output can take several minutes. A 600-second timeout allows for thorough rendering without false timeouts. For development and testing, the timeout can be reduced via the bridge constructor.

## Docker Isolation and Security

The bridge communicates with the external engine through a Docker container. This isolation is not merely a convenience — it is a security requirement. When BlenderBridge executes a Python script, that script runs inside a Docker container with limited filesystem access, no network access, and controlled resource allocation. Even if the AST validator misses a dangerous operation (which should never happen, but defense in depth demands we prepare for it), the Docker container limits the blast radius.

The Docker configuration starts the core services — the Blender worker and the optional local LLM server — by default. Blender is the only rendering engine in the stack. The agents do not depend on a required local \`llm-server\`: their LLM is a cloud multi-provider router aggregated via litellm and configured by provider API keys. GPU resources are relevant to Blender rendering (Cycles benefits greatly from GPU acceleration), and only optionally to the local LLM server if an operator chooses to run local inference instead of using cloud providers.
`

const section3 = `
Each container has its own health checks, restart policies, and resource reservations. The Blender worker reserves GPU resources through the NVIDIA Container Toolkit for Cycles rendering. The optional local LLM server also reserves GPU resources if local inference is used. When agents are backed by cloud LLM providers (API keys), no local inference GPU is required.

<Callout type="tip" title="Blender-First">
DeepBl4nder focuses on a single engine: Blender 4.1+. The DirectorAgent produces a SceneSpec, the BlenderAgent turns it into a deterministic bpy script, and the Blender worker renders it headless with Cycles or EEVEE. Everything in the pipeline — storyboard, camera, materials, animation, compositing — converges on Blender.
</Callout>
`

export default function BridgesPage() {
  return (
    <>
      <MDXRenderer source={section1} />
      <MermaidDiagram chart={mermaidChart1} title="Blender Bridge Architecture" />
      <MDXRenderer source={section2} />
      <MermaidDiagram chart={mermaidChart2} title="Docker Service Architecture" />
      <MDXRenderer source={section3} />
    </>
  )
}