"""add refresh_tokens table

Revision ID: 627437679195
Revises: 6266b3d68bd4
Create Date: 2026-08-24 22:09:28.497429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627437679195'
down_revision: Union[str, Sequence[str], None] = '6266b3d68bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(None, 'artifact_records', type_='foreignkey')
    op.drop_constraint(None, 'artifact_records', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_records', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artifact_records', 'productions', ['production_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.create_foreign_key(None, 'patches', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patches', 'productions', ['production_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patches', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.create_foreign_key(None, 'productions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'productions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'productions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'sequences', ['sequence_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scenes', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sequences', type_='foreignkey')
    op.drop_constraint(None, 'sequences', type_='foreignkey')
    op.create_foreign_key(None, 'sequences', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sequences', 'productions', ['production_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.create_foreign_key(None, 'shots', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shots', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.create_foreign_key(None, 'shots', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'shots', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'sequences', type_='foreignkey')
    op.drop_constraint(None, 'sequences', type_='foreignkey')
    op.create_foreign_key(None, 'sequences', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'sequences', 'productions', ['production_id'], ['id'])
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'scenes', 'sequences', ['sequence_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.create_foreign_key(None, 'productions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'productions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'productions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.drop_constraint(None, 'patches', type_='foreignkey')
    op.create_foreign_key(None, 'patches', 'productions', ['production_id'], ['id'])
    op.create_foreign_key(None, 'patches', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'patches', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'artifact_records', type_='foreignkey')
    op.drop_constraint(None, 'artifact_records', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_records', 'productions', ['production_id'], ['id'])
    op.create_foreign_key(None, 'artifact_records', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
